version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:0.7.3
    ports:
      - "8070:8070"

  pipeline:
    build: .
    depends_on:
      - grobid
    env_file:
      - .env
    environment:
      - GROBID_URL=http://grobid:8070
    volumes:
      - ./pdfs:/app/pdfs
      - ./grobid_output:/app/grobid_output
    restart: unless-stopped
    command: ["python3", "infinite_pipeline.py"]  # 무한 수집 모드